    server {
        listen 80;

        #for multiple backend servers, we can define an upstream block and use it in the proxy_pass directive
        #upstream backend_upstream {
        #server backend:8080;
   # }

        location / {
            proxy_pass http://backend:8080;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            #for multiple proxies, we can use $proxy_add_x_forwarded_for which appends the client IP to the existing X-Forwarded-For header
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # X-Forwarded-Proto is used to indicate the original protocol (HTTP or HTTPS) used by the client. This is important for applications that need to generate correct URLs or perform redirects based on the original request scheme.
            # proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

